
spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    configuration:
      map-underscore-to-camel-case: true # 可选项，开启下划线转驼峰命名规则
    #    type-aliases-package: com.example.yourpackage.entity # 实体类所在的包路径
    mapper-locations: classpath*:mapper/**/*.xml